apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources here are synced by ArgoCD (platform-root Application).
# The ClusterSecretStore is the sole source of truth for AWS Secrets Manager
# integration — it must NOT also be created by Terraform.
resources:
  - cluster-secret-store.yaml
