apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hello-app-test-secret
  namespace: hello
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: hello-app-test-secret
  data:
    - secretKey: username
      remoteRef:
        key: dev/hello-app/test
        property: username
    - secretKey: password
      remoteRef:
        key: dev/hello-app/test
        property: password