apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hello-aws-eks-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: hello-aws-eks-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: REPLACED_BY_KUSTOMIZE
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: dev/argocd/repo/hello-aws-eks
        property: username
    - secretKey: password
      remoteRef:
        key: dev/argocd/repo/hello-aws-eks
        property: password